version: '3'
services:
        web:
                image: physicsflask
                build: .
                ports:
                        - "8012:8012"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped
